name: heroicons_animated_docs
description: Heroicons Animated Flutter docs website.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  google_fonts: ^8.0.1
  heroicons_animated:
    path: ../
  http: ^1.5.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
